/**
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$if (f.repeated)$

  $if (f.message)$
    private final List<$f.messageType$> $f.name$ = new ArrayList<$f.messageType$>();
  $else$
    private final List<$f.boxedJavaType$> $f.name$ = new ArrayList<$f.boxedJavaType$>();
  $endif$

$else$

  $if (f.message)$  
    private $f.messageType$ $f.name$;
  $else$
    private $f.boxedJavaType$ $f.name$;
  $endif$

$endif$
